### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by imajes** [cortesi/devd#1]
Hey,

i tried to install this via ```go get github.com/cortesi/devd```, but this fails -

```
% go get github.com/cortesi/devd
# github.com/cortesi/devd/termlog
src/go/src/github.com/cortesi/devd/termlog/termlog.go:153: undefined: color.NoColor
```
being newish to go, not sure if i've invoked something wrong here by deviating from your build steps... so would appreciate any insight. :)

looks like a great little project.

**Comment by stengaard** [comment]
Works fine for me.

Do you have an old version `github.com/fatih/color` in your `GOPATH`? 

Can you try `go get -u github.com/cortesi/devd` to update the dependencies?

**Comment by stengaard** [comment]
And yes: very cool project! :)

**Comment by cortesi** [comment]
Hi there. I'm also unable to reproduce this - like @stengaard, I suspect that a stale package is most likely to blame. I'll close this ticket for now, but if you're still having trouble after looking at the stale package possibility, please feel free to re-open.

**Comment by imajes** [comment]
Yep, it was a stale package. thanks!
