### ISSUE TITLE
quiet mode

### ISSUE THREAD

**Issue by deepakjois** [cortesi/devd#13]
It would be nice to have a quiet mode which does not log anything to the console.

**Comment by cortesi** [comment]
Hi there. This is certainly something that can be added, but I'd like to understand your use case first. In its default configuration, devd chooses a port to bind to automatically. Completely suppressing output would mean that devd isn't useful unless a) a port was explicitly specified or b) the -o flag is passed to open the browser. This seems a bit inelegant. I'd like to keep things super simple with devd, so maybe if I understand what you're trying to do I can cater for it better in some other way. 

Could you please describe your use case?

**Comment by deepakjois** [comment]
I do not feel the need to have devd running in the foreground, nor do I feel the need for logging every request to the web server. So I would much rather have a quiet option which suppresses that. I guess it is fine to print the port that has been bound and then stop logging any further output. Something like:

```
$ ~/.gopath/bin/devd -qol build/ &
19:19:37: Listening on http://devd.io:8000 (127.0.0.1:8000)
$ gulp watch
…
```

I am using devd right now for two things:
* for web development when I am developing on a React based app. I like to have a static file server, running in the background, and `gulp watch` running in the foreground (as shown above).

* as a static file server on localhost. I use it to preview my blog (which is generated using hakyll) before pushing it online. I run a static file server in the background, and `fswatch` in the foreground to watch for any changes to the source and rebuild the static files.

**Comment by cortesi** [comment]
Thanks for explaining. The -I flag specifies a filter that causes matching requests to be ignored for logging purposes. So, a command like this will only log the binding port and silence all logs for requests:

    devd -I "" .

Does this do what you need?

**Comment by deepakjois** [comment]
Yes, this works. It didn’t occur to me when I first looked at the help options.

Thank you.

**Comment by cortesi** [comment]
Deepak - just a note to let you know that a flag to completely silence devd (-q) has made it into the project after all, and will be in the next release.
