### ISSUE TITLE
Perhaps a name change?

### ISSUE THREAD

**Issue by jv-PintoBobcat** [cortesi/devd#16]
I love the application, but the name makes it hard to find on the world wide web.  If I search for "devd" most of the results are for [some Indian movie](https://en.wikipedia.org/wiki/Dev.D) from 2009, and the rest are for an [existing program](http://www.freebsd.org/cgi/man.cgi?devd(8)) called devd.

**Comment by cortesi** [comment]
Hi there. I like the name devd! If it becomes widely used, it will appear more prominently in the Google results. The clash with FreeBSD's devd is a bit regrettable, but not enough to warrant a name change at this point. The movie is called "Dev. D", which is distinct.

**Comment by jv-PintoBobcat** [comment]
Perhaps we can call it something that's not already used by a well-known application.  Maybe `cat`? Or `grep`?  How about `tar`? :stuck_out_tongue_winking_eye:

**Comment by cortesi** [comment]
I was thinking "Pencil" or "Paper". Those both seem to be in vogue. 

More seriously, though, FreeBSD's devd is nowhere near prominent enough to make a project with the same name silly. The two projects do completely different things, and nobody is going to confuse them. The 3 FreeBSD users who may one day be interested in running devd should feel free to rename the binary to whatever they please. I suggest "ls" for "local server". ;)
