### ISSUE TITLE
Port number is missing from HTTP_HOST

### ISSUE THREAD

**Issue by novak-services** [cortesi/devd#21]
Hello,

devd is really a great idea, something I already searched for some time now.

But when I tried it out on my development system, I had the issue, that the original port number used is not reflected in the HTTP_HOST. I understand, that there where an issue with a different customer, that had problems when the port number is not stripped. But wouldn't it make sense to provide an option for that behavior because at least in my setting, I want to redirect to a different page of my own web-site and the Django framework does create the URL from the HTTP_HOST -- which will be wrong without port number.

Edit:
I would do the change myself and fork the project, but currently I am not working with go, so it would be a big overhead for me. Also I think, that such a switch would be beneficial also for other people using Django or similar frameworks.

Best Regards and thank you for that great tool!

/juergen

**Comment by novak-services** [comment]
Hi,

just one thought on this: It seams to me, that nginx there is also the possibility to decide which port number is transferred. Since for some applications, you might want the original port number (like in my case) and in other cases you might want a different port number.

See:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

Best Regards,

/juergen

**Comment by cortesi** [comment]
Hi there. I've been playing with this today, and we can't just set the host header in this case - as you can see from issue #22, that would break SNI for upstream hosts. This means that we'll have to adopt the "correct" solution, by setting the X_FORWARDED_HOST header. You'll then have to turn on the [USE_X_FORWARDED_HOST](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-USE_X_FORWARDED_HOST) setting in your app, and everything will work. Would that address the issue for you?

**Comment by novak-services** [comment]
Hi Aldo,

yes, that would definitively be a good solution! It seems also to be according to standard or at least according to common practice.

Best Regards,

/juergen

**Comment by cortesi** [comment]
Hi Juergen. Please give that a go, and let me know if it fixes the issue for you.

**Comment by novak-services** [comment]
Hi Aldo, the source code looks good to me. Could you provide a compiled version for Linux 64bit? Than I could try it on my machine. I have no go development system installed.

**Comment by cortesi** [comment]
Sure: I've put a build of the latest master here: http://corte.si/devd-0.3-linux64.tgz

**Comment by novak-services** [comment]
Thanks for the binary!

Yes, this fixes my problem, together with the USE_X_FORWARDED_HOST setting. I tried the new version together with that Django setting and it runs out of the box.

Also for non-Django projects that should be a good solution, because some times your server just needs to know, who was asked in the first place ....

Thank you very much!
