### ISSUE TITLE
Proxying of https sites with SNI does not work

### ISSUE THREAD

**Issue by davidbilge** [cortesi/devd#22]
When trying to proxy our https-site (let's call it xyz.abc) through devd, I get 400 ("Bad Request") errors. The apache logs say: "Hostname xyz.abc provided via SNI and hostname devd.io provided via HTTP are different".

I am not entirely sure how SNI works but it seems that the hostname entered into the browser is transmitted to the webserver. Devd should rewrite this so that it matches the hostname of the proxied webserver.

**Comment by cortesi** [comment]
Thanks, David. I understand the issue now. This actually interacts in a complicated way with #21. Let me ponder it.

**Comment by cortesi** [comment]
Hi David - could you give the latest master a go? I believe it fixes your issue. Please re-open if it does not.

**Comment by davidbilge** [comment]
Okay, I tested your changes in the modd branch and they work fine. Thanks for the fast help!
