### ISSUE TITLE
Error with devd ssl

### ISSUE THREAD

**Issue by llimllib** [cortesi/devd#27]
I'm trying out the new flag and serving my site with: `devd -s .`, but Chrome just downloads a gibberish file. Console says:

`Resource interpreted as Document but transferred with MIME type application/octet-stream: "http://devd.io:8000/".`

Serving without -s works fine; serving with -c and a cert generated with the command you gave in [this issue](https://github.com/cortesi/devd/issues/19) fails in the same way.

Firefox serves a page, but just shows a few error characters. Safari says "Safari can't open the page".

**Comment by llimllib** [comment]
Wait, I was doing something wrong. Closing.

**Comment by llimllib** [comment]
It now works perfectly, no idea what was up. ¯\_(ツ)_/¯

**Comment by cortesi** [comment]
Go's TLS implementation has an idiosyncrasy that makes this confusing. Connecting to a TLS service with a standard browser causes odd behaviour, like file downloads with gibberish that is actually TLS protocol data (https://github.com/golang/go/issues/8720). The behaviour isn't strictly incorrect as defined in the spec, but I think this it is weird and unexpected enough to be blatant bug that needs to be fixed. Until then we're stuck with it, unfortunately.

**Comment by llimllib** [comment]
Weird and unfortunate! Everything has been running smoothly for me since, anyway.

**Comment by AudriusButkevicius** [comment]
A workaround for this is to inspect the first byte in the stream, and decide what to do with the connection.

See: https://github.com/syncthing/syncthing/blob/master/lib/tlsutil/tlsutil.go#L127
