### ISSUE TITLE
Integrated self-test ?

### ISSUE THREAD

**Issue by kad** [cortesi/devd#28]
I'm planning to create formula for homebrew for devd. For that, it would be good if devd can be tested somehow. Currently it's not easily possible.
Maybe it's can be added functionality that would perform HEAD request to itself and validate some headers and exit with result code ?
Or something a bit more complex: start with directory parameter in test mode, try to request some file and validate it by also reading from filesystem ?

Or maybe something else in your opinion can be used as simple test of devd ?

**Comment by cortesi** [comment]
Hi Alexander - a brew formula would be great, so thanks for looking at this. I just a few moments ago committed a change to the build script that might make this easier - "./build single" goes through the dance of compiling the static assets, building the binary, and then removing the compiled asset source files again.

Regarding the self-test. I see that the Caddy webserver does something very, very simple in its formula - [it just starts up the service, and then reads from the process stdout to check that it reports binding to an expected address](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/caddy.rb#L70-L80). We can do this now with devd out of the box, as long as we don't over-specify the port (we select ours automatically). 

If we feel this is not enough, I'd also support adding a special request location to the daemon (/_devd_status or something similar), that just returns "OK". We can then request that URL in the test script (we'd have to parse the actual port out of the stdout output). Initially the fact that we can respond at all is probably enough of a self-test, but eventually we can augment that with whatever we like. Whatever we do, I feel something like verifying the file read from disk would probably be overkill. 

My feeling is that if the Caddy "self-test" is acceptable, we should just do that for now. What do you think?

**Comment by kad** [comment]
Yep, that method might work... unfortunately I'm not that good with Ruby to find way of natively do HEAD or something similar to /_devd_status, so probably minimal functionality of matching "Listening on http://devd.io" would be enough. Will check in the morning :)

**Comment by cortesi** [comment]
Excellent. Do keep me posted on this - I'm very keen to have a brew formula. :)

**Comment by kad** [comment]
btw, somehow build single doesn't work for me :(
v0.1 was building successfully, but current master or v0.3 I'm not able to rebuild on my host.

```
$ ./build single
Making static inclusions...
error reading package: found packages devd (certgen.go) and main (templates.rice-box.go) in /Users/kad/vcs/git/github/go/devd
```

**Comment by cortesi** [comment]
Well, that's weird. Rice does pick up the correct package on my system - it seems to be detecting "main" on yours. Is your repo clean (i.e. with no other non-repo files to confuse rice)? What version of rice are you running?

**Comment by kad** [comment]
rice doesn't show it's own version, but it was compiled on Oct 24 on my system, so I don't think it's too obsolete. in $GOPATH/src/src/github.com/GeertJohan/go.rice  HEAD pointing to c7060fb13da33d0f0df3ca434beb86e3d2bff711

Work directory clean:
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

v0.1 build:
```
$ git co -b v1 v0.1
Switched to a new branch 'v1'
$ go build
$ ls -l devd
-rwxr-xr-x  1 akanevsk  staff  13016884 13 Nov 23:56 devd
$ rm devd
$ git co master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ ./build single
Making static inclusions...
error reading package: found packages devd (certgen.go) and main (templates.rice-box.go) in /Users/kad/vcs/git/github/go/devd
```

v0.2 failing same way :(

**Comment by cortesi** [comment]
Very odd. What's the output of:

    rice -v embed-go

And after that's run, can you manually confirm that the resulting asset file has the package "main" instead of devd?

**Comment by kad** [comment]
Not that much more info:
```
$ rice -v embed-go
2015/11/14 00:05:31 using pwd as import path
2015/11/14 00:05:31 using import paths: [.]
error reading package: found packages devd (certgen.go) and main (templates.rice-box.go) in /Users/kad/vcs/git/github/go/devd
```

for assets, how to check that ?

**Comment by cortesi** [comment]
Ah... it looks like you might have a stale templates.rice-box.go file in there. This is the very file rice is generating, so it's confusing itself... Try removing that and re-running the build command?

**Comment by kad** [comment]
Indeed, removing templates.rice-box.go helped a bit, but not totally:

```
$ ./build single
Making static inclusions...
can't load package: /Users/kad/vcs/git/github/go/devd/cmd/devd/devd.go:7:2: import "github.com/cortesi/devd" is a program, not an importable package
cmd/devd/devd.go:9:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/Users/kad/go/src/github.com/mitchellh/go-homedir (from $GOPATH)
```

**Comment by cortesi** [comment]
That's a new dependency - just install it with go get.
On Sat, 14 Nov 2015 at 11:11 Alexander D. Kanevskiy <
notifications@github.com> wrote:

> Indeed, removing templates.rice-box.go helped a bit, but not totally:
>
> $ ./build single
> Making static inclusions...
> can't load package: /Users/kad/vcs/git/github/go/devd/cmd/devd/devd.go:7:2: import "github.com/cortesi/devd" is a program, not an importable package
> cmd/devd/devd.go:9:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
>     /usr/local/Cellar/go/1.5.1/libexec/src/github.com/mitchellh/go-homedir (from $GOROOT)
>     /Users/kad/go/src/github.com/mitchellh/go-homedir (from $GOPATH)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cortesi/devd/issues/28#issuecomment-156573035>.
>
-- 
--
aldo@corte.si
http://corte.si
@cortesi

**Comment by kad** [comment]
great. made it buildable. Huh, well, time to sleep, tomorrow will look at formula.

**Comment by kad** [comment]
Opened PR  with new formula to homebrew 
https://github.com/Homebrew/homebrew/pull/45978

**Comment by cortesi** [comment]
Great. Closing this issue - I think the minimalist self-test is enough. Thanks a lot for your effort here.
