### ISSUE TITLE
Feature-request: Ability to set custom headers when reverse proxying

### ISSUE THREAD

**Issue by jonaz** [cortesi/devd#29]
Nginx does not handle X-Forwarded-Host well.
It seems i cannot get server_name directive to look at X-Forwarded-Host instead of Host.

Thats why it would be nice to somehow per route be able to inject custom headers (In my usecase Host).

**Comment by cortesi** [comment]
Hey there. Let me take this on board, and think about it. I'm trying to keep devd as lean as possible, so I want to be careful about adding general abilities like header rewriting.

In the meantime, have a look at the [nginx htttp realip module](http://nginx.org/en/docs/http/ngx_http_realip_module.html), which I think does exactly what you want. Please do re-open this ticket if you feel this doesn't do what you need.

**Comment by jonaz** [comment]
Yeah i completely understand. Its a complex thing needing new syntax etc for routes. 

I managed to solve it with a generic server block catching all and then proxying to itself. That way i could set Host to X-Forwarded-Host and then the other server-blocks looking at the Host header could see and use it. 

The reali module does not solve that. It only makes sure the correct source IP can be accessable by the application. It does not modify the Host header before the server_name is processed. 

```
server {
    listen       80;
    server_name  _;

    location / {
		proxy_set_header Host $http_x_forwarded_host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP  $remote_addr;
		proxy_pass   http://127.0.0.1:80;
    }

}

```
