### ISSUE TITLE
Any plans to add brew formula?

### ISSUE THREAD

**Issue by muminoff** [cortesi/devd#3]
Any plans to add `brew` formula for OSX users?

**Comment by cortesi** [comment]
I think that would be very useful, but it will be a while before I can get to it. Contributions will be gratefully accepted! :)

Devd is similar in scope to peco, which [does have a homebrew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/peco.rb). If anyone wanted to look at this, I'd suggest starting there.

**Comment by gcoonrod** [comment]
I took a swing at it. [PR 45268](https://github.com/Homebrew/homebrew/pull/45268)

**Comment by gcoonrod** [comment]
So I'm running into the following error when I try and use devd after installing it with brew per the above referenced formula.

```
> $ devd .                                                                                                                                                                                                                                                                                                                                                       ⬡ 0.10.33
panic: could not locate box "templates"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0x45a08d0, 0x9, 0x1f40)
	/private/tmp/devd20151023-56526-8bz33a/devd-0.1/src/github.com/GeertJohan/go.rice/box.go:110 +0x9a
main.main()
	/private/tmp/devd20151023-56526-8bz33a/devd-0.1/devd.go:289 +0x3c77

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 10 [chan receive]:
github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc8200146e0)
	/private/tmp/devd20151023-56526-8bz33a/devd-0.1/src/github.com/rjeczalik/notify/tree_recursive.go:125 +0x60
created by github.com/rjeczalik/notify.newRecursiveTree
	/private/tmp/devd20151023-56526-8bz33a/devd-0.1/src/github.com/rjeczalik/notify/tree_recursive.go:119 +0x2b0

goroutine 11 [sleep, locked to thread]:
time.Sleep(0x3b9aca00)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/time.go:59 +0xf9
github.com/rjeczalik/notify.gosource(0x0)
	/private/tmp/devd20151023-56526-8bz33a/devd-0.1/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:69 +0x20
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	??:0 +0x31
github.com/rjeczalik/notify.init.1.func1()
	/private/tmp/devd20151023-56526-8bz33a/devd-0.1/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:61 +0x64
created by github.com/rjeczalik/notify.init.1
	/private/tmp/devd20151023-56526-8bz33a/devd-0.1/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:63 +0x44
```

I'm guessing that its a pathing issue, but my go knowledge is fairly limited. Could you take a look @cortesi ?

**Comment by llimllib** [comment]
gcoonrod: no idea on that issue, but why do you have the homebrew installation building the binary rather than just using the released version? (If I've understood it correctly, anyway)

**Comment by gcoonrod** [comment]
@llimllib I was following the example provided by @cortesi.

**Comment by leecade** [comment]
:+1:  cool

**Comment by gcoonrod** [comment]
I've updated the formula as follows but still get the same error when trying to use devd after brewing it.

[Formula](https://gist.github.com/gcoonrod/c5ec92575285fe6cebad)

**Comment by cortesi** [comment]
@gcoonrod: Thanks for working on this! We use rice to package static assets that devd uses. The rice command creates a set of go source files that are compiled into the project for release. In "dev mode" the rice library knows how to find these assets locally. Have a look at the [build script](https://github.com/cortesi/devd/blob/master/build) to see how this is done. One option might be to extend the build script to optionally build just one architecture, and for the brew recipe to just use that.

**Comment by cortesi** [comment]
Looks like the homebrew guys politely declined to officially add a formula for a project this young, which is completely understandable Lets leave this ticket open, and try again a few weeks down the track.

**Comment by DomT4** [comment]
Please do feel free to resubmit in a few weeks. [consul-template](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/consul-template.rb) is a good example of building a `go` formula from source and if you need to set the arch/platform you can pass `ENV` variables to do that like [this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/caddy.rb#L59-L60). Thanks for the interest in `brew`!

**Comment by hrbrmstr** [comment]
In the meantime, here's a homebrew cask tap for the binary release distribution: https://github.com/hrbrmstr/homebrew-devd

**Comment by cortesi** [comment]
Thanks to @kad, we've got a new formula submission to homebrew here:

Homebrew/homebrew#45978

**Comment by cortesi** [comment]
Woot! 

  brew update; brew install devd
