### ISSUE TITLE
devd 0.3 doesn't throttle upstream when uploading file through form (through POST request)

### ISSUE THREAD

**Issue by zuf** [cortesi/devd#30]
I want to test my form for uploading huge files in slow connections.
So I  run devd (v0.3) like this: `devd -o -A localhost -p 3001 -n 800 -u 16 -d 16  http://example.com`

And I saw that uploading speed doesn't throttled. May here some cache issue.

```
12:33:24: GET http://example.com/form
  <- 200 OK 
12:34:18: POST http://example.com/upload
  <- 302 Found 
```

**Comment by cortesi** [comment]
Thanks for spotting this! Please try the latest master, and let me know if you have any further issues.
