### ISSUE TITLE
CGI support?

### ISSUE THREAD

**Issue by mattaltus** [cortesi/devd#31]
Hi,

Any chance of adding CGI support (yes I know it's not 1997 anymore)?

For example something like this, where '%' instead of '=' denotes the cgi path, or something like that...
```
devd /=./pathtohtml /cgi-bin%./pathtocgidir 
```

Thanks
Matt

**Comment by cortesi** [comment]
Sorry, CGI is not on the cards for devd. I realise that it might be handy in some circumstances, but supporting it properly would be at odds with the lean-and-mean ethos of the tool. I've also avoided things like FCGI for the same reason.
