### ISSUE TITLE
Live reload over ssl in Chrome fails when Chrome blocks attempt to load  .devd.livereload over insecure Websocket endpoint ws

### ISSUE THREAD

**Issue by jerryasher** [cortesi/devd#39]
I'm getting this on Chrome Win 7 64.

   Mixed Content: The page at 'https://devd.io/jQuerUIfy/README.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://devd.io/.devd.livereload'. This request has been blocked; this endpoint must be available over WSS.ReconnectingWebSocket.open @ .devd.livereload.js:118ReconnectingWebSocket @ .devd.livereload.js:203(anonymous function) @ .devd.livereload.js:278(anonymous function) @ .devd.livereload.js:302
.devd.livereload.js:118 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.ReconnectingWebSocket.open @ .devd.livereload.js:118ReconnectingWebSocket @ .devd.livereload.js:203(anonymous function) @ .devd.livereload.js:278(anonymous function) @ .devd.livereload.js:302

**Comment by cortesi** [comment]
Hi there. Can you please tell me more about the setup here? I'm unable to reproduce this with the current master.

**Comment by jerryasher** [comment]
Using a command window (cmd.exe) in Win 7 64, I visit a directory and type

```
C:\Users\Jerry\d\workspace>devd.exe --version
0.3

C:\Users\Jerry\d\workspace>devd.exe -osl .\
17:15:33: Listening on https://devd.io (127.0.0.1:443)
17:15:33: GET /
  <- 200 OK 11kB

```

devd opens chrome and displays a directory listing. Chrome indicates that the page is trying to load an unsafe script.

![directory listing with unsafe script warning](http://i.imgur.com/BSLJSHl.png)

The console log says:

```
.devd.livereload.js:118 Mixed Content: The page at 'https://devd.io/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://devd.io/.devd.livereload'. This request has been blocked; this endpoint must be available over WSS.ReconnectingWebSocket.open @ .devd.livereload.js:118
.devd.livereload.js:118 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

```

**Comment by jerryasher** [comment]
Why does git always close issues??

**Comment by cortesi** [comment]
Gotcha. I can reproduce this in master - fix inbound shortly.
