### ISSUE TITLE
Extend listener to use random port and choose interface to listen on

### ISSUE THREAD

**Issue by dg-ratiodata** [cortesi/devd#4]
Hi there,

what do you think abou this:

Extend your listener logic to ask the user on which interface it should listen on using a random port to prevent any collisions. Maybe you could also present the user a list of available interfaces, she/he can choose from. 

Something like https://github.com/fedux-org/local_webserver does. Feel free to copy over bits - MIT licensed. I wrote that web server to serve `middleman-presentation`-presentations which are build up on `reveal.js` (https://github.com/hakimel/reveal.js/)

**Comment by cortesi** [comment]
Hi there,

I see two suggestions here. First, that devd picks a random port to prevent collisions. At the moment, devd tries ports sequentially from 8000, until it finds an open one. This feels "neater", and seems to work well. Second, that we should prompt for an interface to listen on. I want to keep devd an idiomatic command-line app, and prompting for input on startup would be a hindrance more often than it's a help. It's already pretty convenient. We bind to localhost by default, and there's a -a flag to listen on all interfaces. I feel this covers 95% of the use cases. For the other 5% we have explicit binding address specification with -A. 

Thanks for the suggestions - I need external perspectives, so please keep them coming.


Cheers,


Aldo

**Comment by dg-ratiodata** [comment]
> and prompting for input on startup would be a hindrance more often than it's a help. 

I see, tha's why I implemented a timeout ;-)

**Comment by dg-ratiodata** [comment]
BTW: You might want to consider using [UPX](http://upx.sourceforge.net/) to reduce the size of your binaries.

https://github.com/fedux-org/local_webserver/blob/master/scripts/build.sh#L57
https://github.com/fedux-org/local_webserver/blob/master/scripts/build.sh#L59

Unfortunately that does not work with all platforms, but reduces the binaries a lot.

**Comment by dg-ratiodata** [comment]
At least if you want to distribute pre-compiled binaries.
