### ISSUE TITLE
File level routes not working, redirect to '/'

### ISSUE THREAD

**Issue by sirnewton01** [cortesi/devd#43]
Unfortunately, the server that I'm trying to mock maps '/' in paths in the source code to '.' in the URL, which means that I have to resort to file-level routing for the files that I'm developing.

I specify a file-level routes that fall back to the original server like this:

devd -p 9443 -s /=https://localhost:9444/ /ctx/app.foo.bar.bundle.ui.internal.view.baz.MyModule.js=/Users/cmcgee/Documents/workspace4/app.foo.bar.bundle.ui/resources/internal/view/baz/MyModule.js

However, when I GET /ctx/app.foo.bar.bundle.ui.internal.view.baz.MyModule.js it gets redirected with 301 to /

In my version of devd I hacked fileserver/fileserver.go to work around the problem:
diff --git a/fileserver/fileserver.go b/fileserver/fileserver.go
index b1a88d6..06af8ba 100644
--- a/fileserver/fileserver.go
+++ b/fileserver/fileserver.go
@@ -219,7 +219,7 @@ func (fserver *FileServer) ServeHTTPContext(
                upath = "/" + upath
                r.URL.Path = upath
        }
-   fserver.serveFile(logger, w, r, path.Clean(upath), true)
- fserver.serveFile(logger, w, r, path.Clean(upath), false)
  }

Clearly, this is just a hack and I don't know all of the implications of this change. Perhaps, there is even a better way to do the more complex mapping that I need?

**Comment by cortesi** [comment]
Hey there - we've just had some changes in the static file server module, and I'm not able to reproduce this. A request to a long path with dots in the name as you've specified doesn't result in a redirect for me, it correctly serves the specified file. If you're still seeing the issue, please re-open the ticket and I'll take a closer look. It may be some interaction with Windows that I'm not seeing on my dev box.
