### ISSUE TITLE
Strange console logging of encoded chars

### ISSUE THREAD

**Issue by jalkjaer** [cortesi/devd#46]
Encoded query params gets logged somewhat weird:
```
$> devd --version
0.4
$> devd . &
curl -s devd.io:8000/foo?bar=%3A%2F%2F  > /dev/null
```
produces the following log line 
```
10:53:54: GET /foo?bar=%!A(MISSING)%!F(MISSING)%!F(MISSING)
```
Shouldn't it just write the path and params without parsing ?

**Comment by cortesi** [comment]
Hey there - I believe this is a bug that's just been fixed - could you try again with the current master, please?

**Comment by jalkjaer** [comment]
:+1: that fixed it

Keep up the good work -  devd is fantastic :)
