### ISSUE TITLE
32-bit Windows support

### ISSUE THREAD

**Issue by tsutsarin** [cortesi/devd#47]
Does devd support 32-bit Windows 8?
I'm running devd and getting following error on `git bash`:
`bash: /c/Windows/system32/devd: cannot execute binary file: Exec format error`
Also, `cmd.exe` even doesn't see the executable.
I was using  `devd-0.4-windows64.zip`. And `devd-0.4-linux64.tgz` for `git bash` additionaly.

**Comment by cortesi** [comment]
Yes, as the name suggests, that binary was compiled for 64-bit Windows. I haven't tested it, but it should be reasonably easy to just cross-compile for 32-bit Windows (have a look at the [build script](https://github.com/cortesi/devd/blob/master/build)). I wonder how common 32-bit Windows is nowadays?

**Comment by maphew** [comment]
I find myself needing 32bit windows exe. The build script link is broken and I don't see it in repo under a name I recognize. New link or filename?

**Comment by cortesi** [comment]
@maphew Hi there - could you please look at the [build scripts here](https://github.com/cortesi/godist). I've just added a 32-bit Windows distribution there, and you should be able to just run the script from the top-level of the devd project to build it. I might include a 32-bit build in the next release if there's a call for it.

I'm curious - under what circumstances might one encounter a 32-bit Windows system nowadays?

**Comment by maphew** [comment]
The virtual desktop infrastructure (VDI) our organization uses has Win7
32bit machines as the default image. There are 64bit ones too, but they're
slower for some reason.

The VDI are not used for serious work, but some of the people I need to
share development snapshots with use them.

I have a real webserver I can throw snapahot pages up on, so the need for
32bit devd.exe is not great.

It was just easier for me to send an email around saying "go to (here) and
run a batch file" than copy pages to the server. Or at least I thought it
was until I discovered devd I had was 64bit only. ;-)

Matt
