### ISSUE TITLE
serve single file

### ISSUE THREAD

**Issue by nwgat** [cortesi/devd#49]
is it possible?

* `./devd.exe -o -a file.mkv` > http://devd.io/file.mkv
* `./devd.exe -o -a /home/nwgat/files/file.mkv` > http://devd.io/file.mkv

**Comment by cortesi** [comment]
Hi there. This is an interesting idea, but I don't think it's intuitive and I can't think of a clear motivation for it. I'm going to close this ticket, but please feel free to add some explanation of your use case if you feel I've missed something.
