### ISSUE TITLE
ARM Build

### ISSUE THREAD

**Issue by judsonmitchell** [cortesi/devd#5]
This looks like a great project. Any chance your can release a build for ARM machines? I'm hesitant to try compiling it myself....

**Comment by cortesi** [comment]
Yes, I could. ARM Linux?

By the way, you might be very, very pleasantly surprised at how easy it is to cross-compile in Go. Go's tooling is excellent, and cross-compilation generally "just works". This command will procude a working ARM devd binary in the repo:

> env GOOS=linux GOARCH=arm GOARM=7 go build

Yes, it really is that simple.

**Comment by judsonmitchell** [comment]
Yes, ARM Linux would be great. You're right, though, that is easy!

**Comment by judsonmitchell** [comment]
I was able to do it with the help of [gox](https://github.com/mitchellh/gox). Thanks!

**Comment by judsonmitchell** [comment]
I spoke to soon. Running the binary on my ARM machine, I get:
```
panic: could not locate box "templates"
```
How would I build so those files are included?

**Comment by judsonmitchell** [comment]
Ok, got it working by manually installing go.rice and modifying the build bash script in the devd source. If anyone needs the  arm binary before cortesi releases one, I've posted a copy [here](http://loyolalawtech.org/devd-linux-arm.zip).

**Comment by cortesi** [comment]
@judsonmitchell: I would definitely merge a pull request that added ARM support to that build script... ;)
