### ISSUE TITLE
windows64 binary is not a exe file

### ISSUE THREAD

**Issue by nwgat** [cortesi/devd#50]
rename it to .exe and it works

**Comment by davidbilge** [comment]
This is in https://github.com/cortesi/devd/releases/download/v0.4/devd-0.4-windows64.zip - it's also weird that the executable is in a directory called "tmp".

**Comment by cortesi** [comment]
These issues are both now fixed in the build script devd shares with modd (https://github.com/cortesi/godist). Thanks for reporting this!
