### ISSUE TITLE
devd -l doesn't pick up changes to subfolders on OS X

### ISSUE THREAD

**Issue by bsdf** [cortesi/devd#52]
sometime between v0.3 and v0.4 (i believe), `devd -l` stopped picking up changes to subdirectories on my system, only responding to changes in the folder specified. to demonstrate:

```
> devd -ol . &
> echo "hello" >> foo/bar # does not reload
> echo "world" >> baz     # reloads
```

however, given the following modd.conf, both changes are responded to:

```
** {
    daemon: devd -m .
}
```

system info:
OS X 10.11.3
go 1.6 installed via homebrew
devd installed via go get
modd installed via go get

**Comment by bsdf** [comment]
after playing with this a bit, it appears that modd expects an explicit recursive path of `./...` whereas devd will only pass along `.`.

the following diff appears to fix the issue:

```diff
diff --git a/watch.go b/watch.go
index d0eacdd..f188163 100644
--- a/watch.go
+++ b/watch.go
@@ -16,7 +16,7 @@ func (r Route) Watch(ch chan []string, excludePatterns []string, log termlog.Log
 	case *filesystemEndpoint:
 		ep := *r.Endpoint.(*filesystemEndpoint)
 		modchan := make(chan *watch.Mod, 1)
-		_, err := watch.Watch([]string{string(ep)}, batchTime, modchan)
+		_, err := watch.Watch([]string{string(ep + "/...")}, batchTime, modchan)
 		if err != nil {
 			return err
 		}
```

**Comment by cortesi** [comment]
Excellent. Thanks for tracking this down - fix committed.
