### ISSUE TITLE
Docs: Latency flag incorrect

### ISSUE THREAD

**Issue by SlashmanX** [cortesi/devd#6]
The docs say to add latency etc, the command is 
`devd -d 114 -u 51 -l 75 .`

Seeing as `-l` is used for livereload I thought this was wrong. Looking at the base .go file, it looks like the flag for latency is actually `-n`

https://github.com/cortesi/devd/blob/master/devd.go#L201

**Comment by cortesi** [comment]
Good catch, thanks!
