### ISSUE TITLE
Any option for gzip compression?

### ISSUE THREAD

**Issue by rlugojr** [cortesi/devd#64]
Hi Cortesi,
This is an awesome project!  Totally prefer to use this then SimpleHTTPServer.  However, I saw on a review site, which led me here, that they had a screenshot where it showed gzip compression.  Is there a switch or config file change that I am missing or does that not exist in DevD?  If not, then are there plans to include this feature in a future release?  I also searched for plugins but couldn't find anything in a quick Google search.  If you could provide an option for gzip, it would be greatly appreciated!
Thanks!

**Comment by cortesi** [comment]
Hi there - glad you've found devd useful. When livereload is enabled, we request upstream resources with the "identity" encoding so we can easily inject our reload script without needing to decode and re-encode. When livereload is off, we just reflect whatever the client requests and whatever the server sends back. 

I'm guessing you need a different behaviour, but it's not quite clear to me what. Could you describe your use case a bit more, please?

**Comment by cortesi** [comment]
Hi there - I'll close this ticket for now. Please do feel free to re-open and describe what the behaviour is that you expect.
