### ISSUE TITLE
panic running under OSX Sierrra

### ISSUE THREAD

**Issue by phubbard** [cortesi/devd#70]
devd version: 0.5
Runs for a while, then I get

unexpected fault address 0x8c0debfff95
fatal error: fault
[signal 0xb code=0x1 addr=0x8c0debfff95 pc=0x8c0debfff95]

goroutine 50 [running]:
runtime.throw(0x46322c8, 0x5)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc8204f1830 sp=0xc8204f1818
runtime.sigpanic()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8204f1880 sp=0xc8204f1830
github.com/cortesi/termlog.(*Log).format(0xc8205d0e40, 0x4e67201, 0x0, 0x462d2d0, 0x2, 0xc820532f20, 0x1, 0x1, 0x0, 0x0)
	/Users/cortesi/mygo/src/github.com/cortesi/termlog/termlog.go:134 +0x1bb fp=0xc8204f1938 sp=0xc8204f1880
github.com/cortesi/termlog.(*Log).SayAs(0xc8205d0e40, 0x4631ac0, 0x5, 0x462d2d0, 0x2, 0xc820532f20, 0x1, 0x1)
	/Users/cortesi/mygo/src/github.com/cortesi/termlog/termlog.go:215 +0x7f fp=0xc8204f19e0 sp=0xc8204f1938
github.com/cortesi/modd/watch.batch(0xbebc200, 0x1dcd65000, 0x4ec5340, 0x492b800, 0xc8205a85a0, 0x4ec5340)
	/Users/cortesi/mygo/src/github.com/cortesi/modd/watch/watch.go:255 +0x449 fp=0xc8204f1ea0 sp=0xc8204f19e0
github.com/cortesi/modd/watch.Watch.func1(0xbebc200, 0xc8205a85a0, 0xc82065c760, 0x1, 0x1, 0xc8205a8540)
	/Users/cortesi/mygo/src/github.com/cortesi/modd/watch/watch.go:309 +0xa1 fp=0xc8204f1f70 sp=0xc8204f1ea0
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204f1f78 sp=0xc8204f1f70
created by github.com/cortesi/modd/watch.Watch
	/Users/cortesi/mygo/src/github.com/cortesi/modd/watch/watch.go:318 +0x223

**Comment by cortesi** [comment]
Thanks for reporting this. I can reproduce it, and will have a fix out shortly.

**Comment by cortesi** [comment]
It appears that this is due to an issue in Go itself, related to time syscall changes in Sierra. It's been fixed upstream, and all that is needed is for the binaries to be rebuilt with the latest version of Go. I'll have an updated release out later today - in the meantime, building the project with a correct local installation of Go will also eliminate the issue.

**Comment by cgrinds** [comment]
Thanks @cortesi

**Comment by cortesi** [comment]
Release 0.6 is now out, so I'll close this for now. I just know a ton of people with stale binaries are going to get bitten by this, but there's not much we can do about that.
