### ISSUE TITLE
how to prevent devd from adding trailing slash

### ISSUE THREAD

**Issue by stereosteve** [cortesi/devd#73]
I have a rule like `/about=http://somehost/about`

In my browser I visit `http://localhost:5555/about` - the response comes from `somehost` but it's a 404.

When I look on `somehost` I see:

```
"GET /about/ HTTP/1.0" 404 -
```

The flask on `somehost` has strict slash behavior.  Is there some way to prevent this trailing slash from being added?

**Comment by cortesi** [comment]
Hi there - I've just committed a fix that tightens our handling of slashes here. Could you please take a look and see if this works for you?

**Comment by stereosteve** [comment]
Works great... thank you!
