### ISSUE TITLE
Add exclude/ignore filters for watched directory

### ISSUE THREAD

**Issue by TheLQ** [cortesi/devd#8]
Ignore filters would be very handy when other programs edit files in the watched directory. Eg

 - In Typescript you save a .ts file, then the compiler generates a .js file. This causes 2 reloads
 - TourtiseHG makes a temporary hg-checkexec file both periodically and after refresh, which causes the page to reload

In cases like this some kind of --exclude="hg-checkexec*" --exclude="*.ts" switch would be useful.

**Comment by cortesi** [comment]
This is definitely on my desired list as well. I'll hopefully get to it before the next release, and I'd definitely merge a pull request for this. ;)
