### ISSUE TITLE
Native go build?

### ISSUE THREAD

**Issue by mqudsi** [cortesi/devd#85]
Forgive me if I'm missing an incompatibility or external dependency that makes this impossible, but is it possible to enable native build for `devd` via `go build` and deployment via `go install`?

I've managed to build `devd` locally by means of the `gobuild` script in the `godist` repo, but I'm curious if there's any reason local, arch-specific builds cannot be accommodated via the native go tools.

Thank you in advance, and thank you for this wonderful tool.

**Comment by cortesi** [comment]
Hi there. Devd is pure Go with no platform-specific code. You can install the command right from the repo like so:

   go build ./cmd/devd

The build scripts are purely there for cross-platform builds when I do a release.

**Comment by mqudsi** [comment]
Ah, I only tried `go build` without any parameters. Could that default to building devd?
