### ISSUE TITLE
mail.devd.io does not resolved as 127.0.0.1

### ISSUE THREAD

**Issue by dosy4ev** [cortesi/devd#89]
mail.devd.io resoved as googlehosted domain and could'be used for builtin virtual hosting

```
$ host mail.devd.io
mail.devd.io is an alias for ghs.googlehosted.com.
ghs.googlehosted.com has address 209.85.233.121
ghs.googlehosted.com has IPv6 address 2a00:1450:4010:c03::79
```

**Comment by frou** [comment]
Given the readme says:

> Devd uses a dedicated domain - devd.io - to do simple virtual hosting. This domain and all its subdomains resolve to 127.0.0.1

This is a security/privacy issue. Pretty important @cortesi

**Comment by cortesi** [comment]
Agree this is important, and it is on my radar! It's more tricky to fix than it seems at first glance for some trivial internal reasons, and I've been absolutely snowed under recently. 

For anyone reading along, this issue also affects the "calendar", "docs" and "sites" subdomains.

**Comment by cortesi** [comment]
This should now be fixed.

**Comment by frou** [comment]
Thank you for sorting it Aldo... and for providing the domain!
